plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.15'
	id 'io.spring.dependency-management' version '1.1.7'
	id "org.sonarqube" version "7.3.1.8318"
}

group = 'com.innowise'
version = '0.0.1-SNAPSHOT'
description = 'user-service'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

ext {
	liquibaseVersion = "5.0.3"
	postgresVersion = '42.7.13'
	springdocVersion = '3.0.3'
	testContainersVersion = "2.0.5"
	mapstructVersion = '1.6.3'
	lombokMapstructBindingVersion = '0.2.0'
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation "org.liquibase:liquibase-core"
	implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9"
	implementation "org.mapstruct:mapstruct:$mapstructVersion"
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	annotationProcessor 'org.projectlombok:lombok'
	annotationProcessor "org.mapstruct:mapstruct-processor:$mapstructVersion"
	annotationProcessor "org.projectlombok:lombok-mapstruct-binding:$lombokMapstructBindingVersion"

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation platform("org.testcontainers:testcontainers-bom:$testContainersVersion")
	testImplementation "org.testcontainers:testcontainers-postgresql"
	testImplementation "org.testcontainers:testcontainers-junit-jupiter"
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}

sonar {
	properties {
		property "sonar.projectKey", "user-service"
		property "sonar.host.url", System.getenv("SONAR_HOST_URL")
		property "sonar.token", System.getenv("SONAR_TOKEN")
	}
}