server:
  port: 8081

spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false

logging:
  level:
    org.hibernate.SQL: DEBUG